name: sonar3 part2
on:
  workflow_run:
    workflows: [sonar3]
    types: [completed]
jobs:
  sonarcloud_part2:
    name: SonarCloud part2
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the new PR
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Show context
        shell: bash
        run: |
          git remote -v
          git branch
          cat testfile
      - name: Get PR artefacts
        uses: dawidd6/action-download-artifact@v2.19.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: sonar3.yml
          run_id: ${{ github.event.workflow_run.id }}
      - name: Read the PR number
        run: |
          PR=$(cat pr_info/pr_num.txt)
          echo "SONAR_PR_NUMBER=$PR" >> $GITHUB_ENV
          echo SONAR_PR_NUMBER: $SONAR_PR_NUMBER
      - name: Show some debugging
        run: |
          echo SONAR_PR_NUMBER: $SONAR_PR_NUMBER
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
            -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
#            -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
#            -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
#            -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
